package server;

import java.io.Serializable;
//a State represents an entire board
//the board will be represented by a String
//Comparable<State<T>>, Serializable 
public class State<T> implements Comparable<State<T>>{
	
	//setting the Serializable version
	private static final long serialVersionUID = 1L;
	//the current state
	private T state; 
	//the cost to reach the current state
	private double cost; 
	//the previous state to the current one
	private State<T> cameFrom; 
	

	//C'tor
	public State() {
		super();
	}
	public State(T state) {
		super();
		this.setState(state);
	}
	public State(T state, double cost, State<T> cameFrom) {
		super();
		this.state = state;
		this.cost = cost;
		this.cameFrom = cameFrom;
	}
	
	@Override
	public int compareTo(State<T> compare) {
		if (this.state.equals(compare.getState()) 
				&& this.cameFrom == compare.cameFrom)
			return 1;
		else return 0;
	}
	
	//Getters and Settters generated by eclipse
	public T getState() {
		return state;
	}
	public void setState(T state) {
		this.state = state;
	}
	public double getCost() {
		return cost;
	}
	public void setCost(double cost) {
		this.cost = cost;
	}
	public State<T> getCameFrom() {
		return cameFrom;
	}
	public void setCameFrom(State<T> cameFrom) {
		this.cameFrom = cameFrom;
	}

	@Override
	public String toString() {
		return this.state.toString();
	}

	//@Override
	public boolean equals(State<T> compare) {
		if(this.getState().equals(compare.getState()))
			return true;
		else return false;
	}
	
	
	
	

}
